export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

export const ADD_ITEM_NUMBERS = 'ADD_ITEM_NUMBERS'
export const EMPTY_ITEM_NUMBERS = 'EMPTY_ITEM_NUMBERS'
